// <auto-generated />
using System;
using DXC_Assigment_2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DXC_Assigment_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DXC_Assigment_2.Data.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DocumentationVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExitCodeVolume")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlanedDeadend")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegularId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TrueDeadend")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RegularId");

                    b.HasIndex("StageId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Regular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Regulars");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.RegularStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RegularId")
                        .HasColumnType("int");

                    b.Property<int>("StageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegularId");

                    b.HasIndex("StageId");

                    b.ToTable("regularStages");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Deadend")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Module", b =>
                {
                    b.HasOne("DXC_Assigment_2.Data.Regular", "Regular")
                        .WithMany("Modules")
                        .HasForeignKey("RegularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DXC_Assigment_2.Data.Stage", "Stage")
                        .WithMany("Modules")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regular");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.RegularStage", b =>
                {
                    b.HasOne("DXC_Assigment_2.Data.Regular", "Regular")
                        .WithMany("RegularStages")
                        .HasForeignKey("RegularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DXC_Assigment_2.Data.Stage", "Stage")
                        .WithMany("RegularStages")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regular");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Stage", b =>
                {
                    b.HasOne("DXC_Assigment_2.Data.Supervisor", "Supervisor")
                        .WithMany("Stages")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Regular", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("RegularStages");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Stage", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("RegularStages");
                });

            modelBuilder.Entity("DXC_Assigment_2.Data.Supervisor", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
